Feat/#115 채팅 알림 기능 구현
Re-4aliens/backend pull request #116
Opened 2024-06-02 12:36 UTC by coke98

## 🤨 Motivation

- #115 

## 🔑 Key Changes 

- 알림 기능을 위해 sendNotification 메서드를 구현했습니다

## 🙏 To Reviewers 

-

2024-06-04 05:33 UTC, mjj111 requested changes
고생하셨습니다! 댓글 참고해주시고 답변 부탁드리겠습니다 🙇‍♂️

2024-06-04 05:33 UTC, mjj111 commented on src/main/java/com/aliens/backend/chat/service/ChatService.java
> +    private com.google.firebase.messaging.Message createFcmMessage(Message message) {
Message 네이밍이 겹쳐서 해당 메서드에서 코드가 길어졌네요... ㅠ
com.google.firebase.messaging.Message 에 겹치지 않게 
Message 엔티티 네이밍을 변경해보는 것은 어떨까요?!

2024-06-05 03:23 UTC, suhyun0918 approved these changes

2024-06-10 04:57 UTC, mjj111 approved these changes
새로운 이슈에서 해결 부탁드리겠습니다 !

2024-06-10 04:57 UTC, merged