Feat/#12 image uploader 구현
Re-4aliens/backend pull request #18
Opened 2024-01-21 13:28 UTC by mjj111

## 🤨 Motivation

-  #12  

## 🔑 Key Changes 

- S3 를 사용하기 위해 의존성 추가했습니다.
- 파일 업로드시, 먼저 MulitpartFile 을 로컬에 저장하고, 로컬에 저장된 파일을 S3에 업로드 후 로컬 파일은 삭제합니다.
-  외부 리소스인 S3 에 대해 테스트 코드를 작성하고자, S3Mock을 활용하였습니다. 

## 🙏 To Reviewers 

-  S3 Mock 사용하려고 Config 적용하는데 애를 먹었네요 ㅋㅋㅋ ㅠ

2024-01-22 07:32 UTC, Oniqued approved these changes
외부 서비스인 S3를 테스트 하기란 쉽지 않군요 

코드리뷰 남겼습니다 ! 
고생하셨습니다 🤗

2024-01-22 07:32 UTC, Oniqued commented on src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
> +    }
우와.. 이렇게 깔끔하게 테스트 가능하다니... 대단하네요 ! 
LGTM

2024-01-22 07:32 UTC, Oniqued commented on src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
> +    }
이 테스트는 test.png 라는 파일이 있을때만 성공하는 테스트이지 않을까요?
메번 테스트 성공을 보장한다고 보긴 힘들것 같아요..!

2024-01-22 07:32 UTC, Oniqued commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
코드 잘 봤습니다 ! 

제가 게시판 사진 첨부를 구현할땐, 
1. s3에 업로드 후, 파일 링크를 s3에서 반환
2. DB에 (첨부파일 ID, 게시글 ID, 파일 원본 이름, S3에 저장된 파일이름)을 저장. 
3. 게시글 조회 시, 파일 링크를 불러올 수 있도록 함

이렇게 해서 구현했는데, 이 코드는 로컬에도 파일을 저장하고 S3에도 파일을 저장하도록 구현되어있다고 해석하면 될까요 ! 

(잘못 해석했다면 죄송합니다 ㅠ)

2024-01-22 10:11 UTC, coke98 requested changes
파일 시스템 I/O를 추가적으로 거치는 이유가 궁금합니다. 이로 인해 발생할 수 있는 리소스가 필수적인 것인지 알고 싶어요!

2024-01-22 10:11 UTC, coke98 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +                fos.write(file.getBytes());
request의 multipartFile을 S3로 바로 업로드하는 방법 대신 추가적인 I/O작업을 사용한 이유가 있는지 궁금합니다!

2024-01-22 10:11 UTC, coke98 commented on src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
> +    }
LGTM

2024-01-22 10:11 UTC, coke98 commented on src/test/java/com/aliens/backend/uploader/AwsS3MockConfig.java
> +public class AwsS3MockConfig {
테스트 환경의 S3는 실제 환경과는 어떤 차이가 있는건가요? 궁금궁금

2024-01-22 12:03 UTC, mjj111 commented on src/test/java/com/aliens/backend/uploader/AwsS3MockConfig.java
> +public class AwsS3MockConfig {
실제 S3에 요청을 보내는 것이 아니라Mock객체인 S3Client로 요청을 보내게됩니다!
즉, S3에는 파일이 업로드 되지 않는거죠!

2024-01-22 12:07 UTC, mjj111 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +                fos.write(file.getBytes());
Springboot 서버에서 바로 MultipartFile을 S3로 보내는 방식이 없습니다! 
S3Client는 URL을 따라가서 저장된 File을 직접 업로드하는데요, 
물론 메모리에 담았다가 보낼 수도 있지만, 얼마 없는 메모리에 해당 파일을 저장했다가 보내기에는 부하가 어느정도인지 가늠하기 힘들다 판단했습니다. (게시판과 프로필 사진 업로드 요청의 정도를 가늠할 수 없었습니다) 
그래서 메모리에 올려놓기보다는 disk에 저장했다가 보내고 삭제하는 방식으로 구현했습니다!

++ 물론 MultipartFile을 직접 S3로 프론트에서 보낼 수도 있긴합니다..! 다만 조금 복잡해지고 프론트에 작업이 필요합니다. 해당 URL 참고하셔서 이해하시면 좋을 것 같습니다 🙋‍♂️https://techblog.woowahan.com/11392/

2024-01-22 12:15 UTC, mjj111 commented on src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
> +    }
Mock 객체를 사용하고 있어서, 어떤 path나 문자열을 넣어도 성공합니다!

2024-01-22 12:17 UTC, Oniqued commented on src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
> +    }
> Mock 객체를 사용하고 있어서, 어떤 path나 문자열을 넣어도 성공합니다!

그렇군요!

2024-01-22 13:03 UTC, Oniqued approved these changes

2024-01-22 15:07 UTC, mjj111 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +                fos.write(file.getBytes());
찾아보니 바로 가능한 방법이 있네요! 
매우 무거운 I/O 작업과 로컬에도 파일이 저장된다는 점( 쓸데없는 자원을 낭비하여, 이 때문에, 별도로 file을 지우는 작업에 대한 고려..하는 단점)이 좋지 못하네요.
다른 방법으로 구현하겠습니다! 감사합니다 🙇‍♂️

2024-01-24 10:59 UTC, coke98 approved these changes

2024-01-24 10:59 UTC, coke98 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +        return request.files().parallelStream().map(this::uploadToS3).toList();
로직 변경 확인했습니다! LGTM 👍

2024-01-24 11:06 UTC, mjj111 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
로컬에 저장한 뒤에 S3에 업로드 후, 로컬에 저장한 파일을 지우는 방식이었습니다!
여러분들의 리뷰덕에 더 고민하여, 로컬 저장을 제외하여 다시 구현하였습니다 .
감사합니다 🙇‍♂️♥️

2024-01-24 11:08 UTC, merged