Feat/#15 회원도메인 구현
Re-4aliens/backend pull request #24
Opened 2024-01-25 02:46 UTC by mjj111

## 🤨 Motivation

- #15 

## 🔑 Key Changes 

- 회원 도메인을 구현합니다.

## 🙏 To Reviewers 

-

2024-01-25 02:54 UTC, Oniqued approved these changes

2024-01-29 05:55 UTC, Oniqued requested changes

2024-01-29 05:55 UTC, Oniqued commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +    private MemberStatus status = MemberStatus.NOT_APPLIED_NOT_MATCHED;
회원이 매칭을 신청했는지, 매칭이 되었는지 여부를 회원 서비스에서 상태를 저장하는 컬럼인가요?!

매칭 도메인에서 현재 매칭 회차, 회원ID를 기반으로 조회할 수 있도록 구현하기로 했던것 같은데 
제가 이해한 부분이 맞는지 이 부분 설명 부탁드립니다..!

<img width="446" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/fe28096a-c5bc-4269-8117-01769888f596">

2024-01-29 05:55 UTC, Oniqued commented on src/main/java/com/aliens/backend/email/service/EmailService.java
이벤트 처리 방식이 적용되었군요 👍

2024-01-29 16:47 UTC, coke98 approved these changes

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +        return files.stream().map(this::uploadToS3).toList();
어디 사용될까 생각했는데, 게시글 같은 경우 한번에 여러개의 파일을 업로드할 필요가 있겠네요

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/global/property/S3UploadProperties.java
> +    @Value("${cloud.aws.default.file-url}")
프로퍼티로 관리하는 거 조아요

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/email/service/EmailSender.java
> +        return temporaryPasswordEmail;
추상화 수준이 잘 나뉘어져 있어서 읽기 편해요~

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/member/controller/dto/request/SignUpRequest.java
> +                            String aboutMe) {
레코드가 편하긴하네요

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/member/domain/MemberStatus.java
> +public enum MemberStatus {
수현님의 의견이 있긴했지만, 만약 매칭 상태를 나타낸다면 MatchingStatus같은 네이밍도 고려할 수 있을 것 같아요
MemberStatus를 처음 떠올렸을땐 회원 "일시정지", "탈퇴"와 같은 일반적인 회원 상태가 생각나더군요

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/member/domain/Image.java
> +    String url;
이미지를 정규화해서 테이블로 만드는 것도 좋은 방법이겠네요 기존에 비정규화되어있던 방식에서는 ImageUrl컬럼 하나로 관리되고 있었는데, name과 url을 분리하여 관리하는 점도 좋아보입니다

2024-01-29 16:47 UTC, coke98 commented on src/test/java/com/aliens/backend/member/MemberInfoServiceTest.java
> +    }
컨트롤러 테스트와, 서비스 테스트에서 중복되서 사용되는 createSignUpRequest 메서드가 중복되네요. 
현재코드는 유지보수 과정에서 signUpRequest가 변경될 경우 컨트롤러와 서비스 테스트 코드 모두 변경해야합니다.

다른 셋업 메서드들도 MemberTestUtil 같은 별로의 클래스로 관리하는 건 어떨지 고민해보면 좋을 것 같습니다
클래스마다의 역할도 잘 분리되고, 중복도 줄여 테스트 데이터들에 대한 유지보수도 편해지는 장점이 있을 것 같아요

2024-01-29 16:47 UTC, coke98 commented on src/main/java/com/aliens/backend/member/sevice/MemberInfoService.java
> +    private String getRandomPassword() {
그냥 생각난건데 임시 비밀번호 생성용 클래스를 따로 만들어서 역할을 분리하고(매직넘버도 상수화), 올바른 패스워드를 생성하는지 테스트하는 것도 예뻐 보일것 같아요. 

현재는 어떤 임시 패스워드를 만들더라도 String값이기만 하면 MemberResponse.TEMPORARY_PASSWORD_GENERATED_SUCCESS.getMessage()를 반환하긴하네요

2024-01-29 17:09 UTC, Oniqued approved these changes

2024-01-29 17:09 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +    private MemberStatus status = MemberStatus.NOT_APPLIED_NOT_MATCHED;
MemberStatus 하면 탈퇴 상태.. 이런게 떠오릅니다 ! 
MatchingStatus는 어떨까요?

2024-01-29 17:09 UTC, Oniqued commented on src/main/java/com/aliens/backend/global/property/S3UploadProperties.java
이렇게 관리 하니까 너무 좋더라구요 ! 무엇보다 @Value(${"~"})들이 서비스에 눈에 띄지 않아서 좋아요

2024-01-29 17:09 UTC, Oniqued commented on src/main/java/com/aliens/backend/member/controller/dto/request/SignUpRequest.java
레코드를 쓰니, 매번 반복되는 생성자같은 코드들이 안보여서 좋았어요 !

2024-01-30 06:48 UTC, mjj111 commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +    private MemberStatus status = MemberStatus.NOT_APPLIED_NOT_MATCHED;
UI 첫 화면에서 매칭과 신청 상황에 따른 상태에 따라, 장면이 달라집니다!
그래서, 프론트엣 따로 해당 홈화면 접근시 상태를 요청하기 때문에 MemberStatus 가 추가되었습니다

2024-01-30 06:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
> +        return files.stream().map(this::uploadToS3).toList();
맞습니다! 오버로딩 해놓기는 했는데, 해당 이미지 업로드의 경우 저만 사용해서.. 
사용하다가 불편하면 다른 네이밍으로 메서드 분리하고자합니다!

2024-01-30 06:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/property/S3UploadProperties.java
> +    @Value("${cloud.aws.default.file-url}")
깔끔합니다 👍😉

2024-01-30 06:52 UTC, mjj111 commented on src/main/java/com/aliens/backend/member/domain/MemberStatus.java
> +public enum MemberStatus {
withdraw 컬럼이 있어서 탈퇴한 유저의 경우 토큰 발급이 안되고, 
DB에서는 withdraw 컬럼이 true 로 되어있어요! 그래서 괜찮다 생각했는데..
일시 정지가 있었네요..! 일시 정지의 경우 memberStatus에 포함시켜도 좋을거 같아요. 
홈화면에서 상태 요청시 일시정지 회원의 경우, 로그인은 되지만 아무 기능에도 접근하지 못하게 막으면 좋을 것 같군요 !

결론적으로 MemberStatus에 일시정지, 매칭관련 상태를 갖고있는건 어떨까요?

2024-01-30 06:53 UTC, mjj111 commented on src/main/java/com/aliens/backend/member/domain/Image.java
> +    String url;
name 의 경우 S3에 파일을 삭제해야하기 때문에 필요했고, 
URL은 이미지 파일을 읽는 주소를 저장하기 위해서였습니다. 
정규화해서 관리하니, 게시판과 회원 프로필 모두 Image 테이블로 같이 관리가 가능해져요! 👍

2024-01-30 06:55 UTC, mjj111 commented on src/main/java/com/aliens/backend/member/sevice/MemberInfoService.java
> +    private String getRandomPassword() {
비밀번호 생성용 클래스를 따로 두는거 좋네요! 이슈로 파두도록 하겠습니다 👍
 현재는 바로 작업이 불가해서 머징 후 작업 때, 해당 이슈와 함께 작업해놓도록 하겠습니다 🙆‍♂️

2024-02-03 11:48 UTC, merged