Feat/#33 매칭 회차 업데이트, 조회 기능 개발
Re-4aliens/backend pull request #34
Opened 2024-01-31 07:27 UTC by Oniqued

## 🤨 Motivation

- https://github.com/Re-4aliens/backend/issues/33

## 🔑 Key Changes 

- 매칭 회차는 매주 월, 목요일마다 업데이트되고, 관리되어야합니다. 
- 매칭 회차를 조회할 수 있도록 Id가 가장 큰 값을 반환하도록 쿼리를 작성했고 테스트 성공했습니다.

## 🙏 To Reviewers 

-

2024-02-07 04:42 UTC, mjj111 requested changes
적은 시간에... 이정도량의 코드를..! 
너무 고생하셨습니다.  리뷰 확인해주시고 의견 부탁드리겠습니다😉🙇‍♂️

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/error/MatchingError.java
> +    INVALID_LANGUAGE_INPUT(HttpStatus.BAD_REQUEST, "MA5", "두 선호 언어가 같을 수 없음"),
프론트 오류로 인해 생길 수 있는 입력 예외도 추가하셨군요 👍🙆‍♂️

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/property/MatchingTimeProperties.java
> +    public Long getMatchingValidHours(final DayOfWeek dayOfWeek) {
MatchingTimeProperties 마저 이런 메서드를.. 달다니,, 좋네요 👍

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/success/SuccessResponse.java
> +public class SuccessResponse<T> {
SingleMap을 통해 전달하던 Response를 이렇게 매핑해서 하다니 더 깔끔하네요👍

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/dto/input/MatchingInput.java
> +            if (firstPreferLanguage.equals(secondPreferLanguage)) {
현재 prefeLanguage 두 개가 동일한 것인지 검증하는 동작을 위해 해당 클래스가 있는 것 같아요! 
만약 그렇다면 트레이드 오프해서 private 메서드 하나로 서비스 단에서 검증해주거나 record에 커스텀한 @Validate를 넣어주는 것은 어떨까요?? 
첫 번째 두 번째 선호언어 검증을 위해 수정하고자 한다면 해당 클래스를 다 이해하고 수정해야 하는 오버헤드와 메서드 하나로 접근해서 수정하여 쓰이는 오버헤드랑 비교한다면 메서드 하나가 더 적합할 것 같습니다! 
혹은 @Validate 을 커스텀해서 record 에 삽입해주는건 어떨까요? 
한눈에 해당 클래스가 검증을 수행하는가 확인할 수도 있고 다른 DTO에도 수월하게 적용할 수 있으니깐요! 
현재 적용되고 있는 방식은 하나의 요청에 검증을 위한 객체가 추가되어 두 개의 객체를 생성하게되고, 이해해야하는 클래스가 추가되며 검증을 수행하는 절차를 이해하기 조금 어려운 것 같습니다..!

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/dto/request/MatchingRequest.java
> +        public MatchingApplication toEntity(MatchingRound matchingRound) {
Dto에서 toEntity로 사용하기 보다는 엔티티가 from 정적 메서드로 엔티티를 생성하는건 어떨까요?? 
해당 객체의 생성 책임을 엔티티가 갖도록 DTO에서는 transfer 책임만 갖도록 하는게 더 좋아보입니다!

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/domain/MatchingRound.java
> +    private LocalDateTime matchingRequestStartTime;
matching 이라는 접두사를 제거해도 좋을거같아요!

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/domain/MatchingRound.java
> +public class MatchingRound {
시작 시간과 끝나는 시간을 재는 이유가 궁금합니다!
더불어, 검증 시간을 기록 하는 이유도 궁금합니다!

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingApplicationRepository.java
> +    List<MatchingApplication> findAllByMatchingRound(MatchingRound matchingRound);
해당 쿼리에 JPQL 작성하지 않아도 동작하지 않나요!?

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingRoundRepository.java
> +    Optional<MatchingRound> findCurrentRound();
내림차순으로 두고  Limit을 통해 하나만 뽑으면 되지 않을까요?

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +        matchingApplicationRepository.save(matchingApplicationRequest.toEntity(currentRound));
toEntity 보다는  Entity.from(request) 형식이 더 맞아 보입니다!
DTO가 엔티티 생성 책임까지 갖고있어보여요!

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +                matchingApplicationRepository.findById(MatchingApplicationId.of(currentRound, memberId))
예외를 뱉는 경우에는  private 메서드로 따로 분리해서 추상화해도 좋을거같아요!
추후에 다른 메서드에서도 동일하게 사용할 수 있으니 더 좋습니다👍

2024-02-07 04:42 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingService.java
> +        for (Participant participant : participants) {
이...이중 for문..! 
for 문의 길이가 길어질 수록 위에 작성된 명령어의 흐름을 기억하고 있어야해서 
이해가 힘들어 질 수 있습니다.(개인의 기호가 조오금 들어가 있습니다 ㅎ 죄송합니다.)
 현재 Stream을 저희 프로젝트에서 컨베션처럼 사용하고 있어서 해당 이중 for문을 Stream으로 작성해주시면 더 좋을 것 같아요!
 ex) participants.stream().map(MatchingResult::of)....

2024-02-07 04:42 UTC, mjj111 commented on src/test/java/com/aliens/backend/matching/integration/MatchingApplicationApiTest.java
> +//                .andDo(document("post-matching-application",
호옥시 주석처리 하신 이유가 있을까요?

2024-02-07 04:42 UTC, mjj111 commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
> +    @Transactional
혹시@Transactional은 이전에 말씀 드린바와 같이 지양하는게 어떨까 합니다! 🙋‍♂️

2024-02-07 04:55 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/controller/dto/input/MatchingInput.java
> +            if (firstPreferLanguage.equals(secondPreferLanguage)) {
우선, 이 클래스는 사용자의 Input만을 받는 클래스로써, 사용자가 입력할 수 있는 [1선호 언어]와 [2선호 언어]만을 받습니다 ! 
```
@PostMapping("/applications")
    public ResponseEntity<?> applyMatch(final @Login LoginMember loginMember,
                                        final @RequestBody MatchingApplicationInput matchingApplicationInput) {
```

여기서 이렇게 사용되지요, 
그리곤 Service에 Input을 넘길때, input을 바로 넘기는게 아닌, input을 toRequest 메서드를 이용해 memberId를 같이 붙여서 서비스에 전달하고 있습니다.
```
matchingApplicationService.saveParticipant(matchingApplicationInput.toRequest(loginMember.memberId()));
```
즉, preferLanguage가 동일한지 검증하기 위한 클래스가 아닌, 사용자 입력을 직접적으로 받는 클래스입니다. 
그리고 ~Request 형태로 서비스에 memberId가 함께 전달합니다. 

- record에 커스텀한 @Validate를 넣어주는 것은 어떨까요?? << 이 방법이 너무 마음에 드네요 ! 수정토록 하겠습니다

2024-02-07 05:12 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/integration/MatchingApplicationApiTest.java
> +//                .andDo(document("post-matching-application",
앗 이 부분은 통합 테스트 부분인데 아직 구현이 덜되어 있습니다. 커밋에 딸려 들어갔네요...

사용자 인증이 필요한 테스트라 헤메다가 일단 주석 처리 했었습니다.

2024-02-07 05:13 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
> +    @Transactional
알겠습니다 !

2024-02-07 05:59 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingService.java
> +        for (Participant participant : participants) {
매칭 알림이 구현되면 수정토록 하겠습니다 !

2024-02-07 09:49 UTC, mjj111 requested changes
회의에서 라이브 리뷰한 사항들입니다!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingRoundService.java
> +        matchingRoundRepository.save(MatchingRound.of(LocalDateTime.now(clock), matchingTimeProperties));
한 줄에 충분히 많은 메서드가 들어간 느낌이 듭니다..!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/property/MatchingRuleProperties.java
> +        return Integer.parseInt(maxTries);
yml에서 숫자로 적으면 알아서 바인딩 해줍니다! 
굳이 Integer.parseInt 를 사용하실 필요없어보여요!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +    private void initialize(final List<MatchingApplication> matchingApplications) {
initialize 는 operateMathcing 메서드 아래에 위치하면 좋을 것 같습니다!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        List<Participant> participants = null;
전역변수랑 네이밍이 같아서 이해가 조금 어려울 수도 있을 것 같아요. 
차라리 전역분수가 아니라 매개변수로 해서 관리하는게 더 수월해보입니다.

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +            candidates = new LinkedList<>(getParticipantsLessThan(matchingRuleProperties.getMaxPartners()));
메서드 두 개가 있어서 이해가 개인적으로 어렵습니다,,! 분리하면 더 좋을 것 같아요

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        for (Participant participant : participants) {
현재 Stream을 주로 사용하고 있기 때문에 if문으로 들어간 동작 메서드로 분리해서 Stream 으로 작성해주시면 좋을 것 같습니다!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        while (!isExceededMaxPartners(relationship, participant) && !isExceedMaxTries(tries) && !candidates.isEmpty()) {
조건을 바로 읽을 수 있게 추상화하면 더 좋을 것 같아요!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +    private List<Participant> participants = new ArrayList<>();
일급 컬렉션으로 따로 관리면 더 좋을 것 같아요!
그러면 해당 비즈니스 클래스에서 private 메서드도 분리할 수 있어보입니다

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/MatchingController.java
> +    @Autowired
생성자 주입으로 의존성 주입이 될텐데 @Autowired를 넣어주신 이유가 있으실까요?

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/MatchingController.java
> +        matchingApplicationService.saveParticipant(matchingApplicationInput.toRequest(loginMember.memberId()));
saveParticipant(LoginMember, MatchingApplicationRequest) 를 받는 형식으로 수정하면 더 깔끔할거 같아요!

2024-02-07 09:49 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/dto/response/MatchingResponse.java
> +                    matchingApplication.getId().getMatchingRound().getRound(),
메소드를 체이닝 하지않고 분리할 수 있어보입니다!

2024-02-08 04:34 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/controller/dto/request/MatchingRequest.java
> +        public MatchingApplication toEntity(MatchingRound matchingRound) {
전적으로 동의합니다. DTO에서 엔티티를 생성하는것은 오류가 있어보이네요 !

2024-02-08 04:34 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +        matchingApplicationRepository.save(matchingApplicationRequest.toEntity(currentRound));
압도적으로 동의합니다

2024-02-08 04:35 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +                matchingApplicationRepository.findById(MatchingApplicationId.of(currentRound, memberId))
맞아요.. currentRound는 메서드 분리 잘 해놓고 왜 그랬던 걸 까요... ㅠㅠ 
수정하겠습니다 !

2024-02-08 04:35 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingRoundService.java
> +        matchingRoundRepository.save(MatchingRound.of(LocalDateTime.now(clock), matchingTimeProperties));
나중에 저도 읽기 힘들어질 수 있겠네요 !
무엇을 저장할 것인지 따로 코드라인 분리해서 가독성에 신경쓰도록 하겠습니다 !

2024-02-08 04:36 UTC, Oniqued commented on src/main/java/com/aliens/backend/global/property/MatchingRuleProperties.java
> +        return Integer.parseInt(maxTries);
또 알아가네요... ! 감사합니다

2024-02-08 04:36 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +    private void initialize(final List<MatchingApplication> matchingApplications) {
그렇군요. private 메서드라 public 메서드 위에 있는것은 보기 좋아보이지 않네요 !

2024-02-08 04:37 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        List<Participant> participants = null;
그렇네요. 아래에 this.participants과  같이 가독성에 영향을 끼치게 되는군요... 매개변수로 관리할 수 있도록 고민하겠습니다 !

2024-02-08 04:37 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +            candidates = new LinkedList<>(getParticipantsLessThan(matchingRuleProperties.getMaxPartners()));
그렇네요. LinkedList<>의 생성자에 메서드가 들어가다 보니까 무슨 뜻인지 잘 이해하기 힘들겠군요

2024-02-08 04:38 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        while (!isExceededMaxPartners(relationship, participant) && !isExceedMaxTries(tries) && !candidates.isEmpty()) {
동의합니다 ! while문의 조건이 저렇게 길어질 필욘 없을 것 같아요

2024-02-08 04:39 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +    private List<Participant> participants = new ArrayList<>();
아아... 일급 컬렉션 생각을 못했네요 감사합니다! 
일급 컬렉션으로 관리한다면 participant와 관련된 메서드를 전부 일급 컬렉션에 넣을 수 있으니 코드가 더욱 줄겠네요! 
정말 좋은 아이디어네요!

2024-02-08 04:51 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/controller/MatchingController.java
> +    @Autowired
맞습니다. 생성자 주입으로 @Autowired를 생략해도 되는 것이 맞습니다. 
그러나 @Autowired는 생성자가 2개 이상인 경우, 생략을 할 수 없습니다. 
그렇기 때문에, 어떤 클래스는 @Autowired를 생략하고, 어떤 클래스는 @Autowired를 생략하지 않는 경우가 생길 수 있기 때문에 붙였습니다. 
AA 상황에서는 XX로 해야하고,
BB 상황에서는 YY로 해야한다 등의 규칙이 있으면 복잡해질 것 같아
무조건 다 붙여버렸습니다... 

+++ 팀의 컨벤션이 더욱 중요하니, @Autowired를 생략하도록 하겠습니다 ! 생성자가 2개 이상인 경우도 잘 없고...(습관적으로 붙여버렸네요)

2024-02-08 04:52 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/controller/MatchingController.java
> +        matchingApplicationService.saveParticipant(matchingApplicationInput.toRequest(loginMember.memberId()));
굳이 input을 toRequest 할 필요가 없도록 하는거군요 !

2024-02-08 04:53 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/controller/dto/response/MatchingResponse.java
> +                    matchingApplication.getId().getMatchingRound().getRound(),
바로 그렇습니다.... get메서드를 수정해야겠군요

2024-02-08 06:48 UTC, coke98 approved these changes
LGTM!

2024-02-08 06:48 UTC, coke98 commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
> +        mockClock.mockTime(VALID_TIME);
시간을 목으로 진행하는 경우를 처음보는데, 가능한 시간, 불가능한 시간을 조정할 수 있다는 게 처음보면서 신기했네요. 고민하신게 보여요

2024-02-08 06:48 UTC, coke98 commented on src/test/java/com/aliens/backend/matching/util/MockTime.java
> +    VALID_TIME(LocalDateTime.of(2024, 1, 29, 10, 0));
이렇게 관리하는거 너무 좋아요
추가로 MATCHING_VALID_TIME 처럼 더 의미를 자세하게 설명할 수 도 있을 것 같아요, 처음 보시는 분들의 경우 어떤것이 가능한 시간이라는것인지 궁금할 수 있을 것 같네용~~
추후에 테스트시 조정해야하는 시간 종류가 늘어날 경우에도 명확하게 다른 Enum과 분리될 수 있을것 같습니당

2024-02-08 06:48 UTC, coke98 commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingRoundServiceTest.java
> +        LocalDateTime monday = LocalDateTime.of(2024, 1, 29, 0, 0);
테스트에서 요렇게 관리되고 있는 부분들도 요구사항이 변경된다면, 테스트마다 변경해줘야하니 
만드신것 처럼 의미를 명확하게 보여줄 수 있는 이넘이나, 상수화하는 방법도 좋아보여요

2024-02-08 06:48 UTC, coke98 commented on src/test/java/com/aliens/backend/matching/unit/business/MatchingApplicationGenerator.java
> +        Random random = new Random();
테스트용 제너레이터 만든거 좋아요!
Random객체랑 Language[] languages = Language.values(); 는 클래스 멤버로 둬서 재사용 가능하게 둬도 좋을것 같아용

2024-02-10 04:01 UTC, mjj111 approved these changes
확인 했습니다! 다음 이슈에서 변경 부탁 드리겠습니다~!

2024-02-10 04:02 UTC, merged

2024-02-10 11:50 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
> +        mockClock.mockTime(VALID_TIME);
이 부분 예쁘게 봐주셔서 감사합니다 ㅎㅎ 
LocalDateTime.now()를 사용하는 서비스 코드를 모킹할 수 없어 Clock을 모킹하고 주입 받아 테스트 할 수 있도록 구조를 변경했습니다 !

2024-02-10 11:50 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/util/MockTime.java
> +    VALID_TIME(LocalDateTime.of(2024, 1, 29, 10, 0));
좋은 지적 감사합니다 ㅎㅎ

2024-02-10 11:51 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/unit/service/MatchingRoundServiceTest.java
> +        LocalDateTime monday = LocalDateTime.of(2024, 1, 29, 0, 0);
그러네요 ! 놓칠 수 있는 부분 지적 감사합니다

2024-02-10 11:52 UTC, Oniqued commented on src/test/java/com/aliens/backend/matching/unit/business/MatchingApplicationGenerator.java
> +        Random random = new Random();
재사용 가능하도록 바꾼다면 더욱 좋겠네요 ! 감사합니다

2024-02-10 11:52 UTC, Oniqued commented
> 확인 했습니다! 다음 이슈에서 변경 부탁 드리겠습니다~!

따끔한 피드백 감사합니다 !!

2024-02-11 02:39 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/domain/MatchingRound.java
> +public class MatchingRound {
해당 속성은 현재 회차에 신청 가능한 시간대인지 확인이 필요해서 넣은 속성입니다. 
또한, validStart, validEnd 같은 경우, 해당 회차의 매칭이 언제까지 유효한 매칭인지 알기 위해 기록해놓은 속성입니다. 
이 속성은 채팅 도메인에서 활용됩니다. 앞선 회의에서 현석님이 이 속성은 매칭 도메인에서 넣는게 더 적절하다고 하셨고, 저도 그게 맞는것 같아 추가되었습니다

2024-02-11 02:39 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingApplicationRepository.java
> +    List<MatchingApplication> findAllByMatchingRound(MatchingRound matchingRound);
맞는 말씀이네요 ! 
습관적으로 작성하지 않았나 싶습니다... 수정하겠습니다 !