Refactor/#45 매칭 도메인 리펙토링 및 로직 고도화 (git 충돌 해결)
Re-4aliens/backend pull request #57
Opened 2024-02-14 07:48 UTC by Oniqued

## 🤨 Motivation

- https://github.com/Re-4aliens/backend/issues/45

## 🔑 Key Changes 

- 코드 리뷰의 피드백을 바탕으로 리펙토링을 진행하였습니다. 

## 🙏 To Reviewers 

### 전역변수 to 지역변수에 관하여
 매칭 참가자를 지역변수화 하는 안건에 대하여 피드백을 받고, 이를 바탕으로 구현하던 도중
한가지 의문이 들었습니다. 
저는 '매칭 참가자'를 일급 컬렉션으로 관리했고 이를 계속 매개변수를 통해 전달하도록 구현했는데,
매칭 비즈니스를 생명 주기 관점으로 보면 거의 매 메서드 마다 '매칭 참가자'가 필요합니다. 
'매칭 참가자'를 매개변수로 관리하게 될 경우, 메서드 마다 '매칭 참가자'가 매개변수로 들어가게 되고
변경 관리 및 추적이 힘들어 오히려 가독성이 저하되는 문제점을 발견하였습니다. 
저희가 리포지토리를 매 메서드 마다 매개변수로 넣지 않듯, 
'매칭 참가자'라는 일급 컬렉션 데이터를 전역변수로 관리하여 그 상태가 계속 유지되도록 하며 
나아가 코드가 더욱 간결해지는데에서 얻는 이점이 더 크다고 판단했습니다. 
위 사유로, 일급 컬렉션 전역변수로 관리하도록 구현했습니다.

- 우선 PR만 올려놓습니다. 끝나는 대로 리뷰 요청 문자 발송하도록 하겠습니다.

2024-02-14 07:50 UTC, Oniqued commented
<img width="914" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/07fdad32-4ee4-4c50-86b5-9e59f9d7ecbd">

2024-02-14 07:50 UTC, Oniqued commented
![Uploading image.png…]()

2024-02-14 07:51 UTC, suhyun0918 commented
<img width="813" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/5062873b-e80e-44b1-b3b8-7ebaa7054aa0">

2024-02-14 07:51 UTC, Oniqued commented
<img width="813" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/a2dcc7fe-0ce3-49f9-a2ee-3738b9fabf73">

2024-02-14 07:52 UTC, Oniqued commented
<img width="805" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/3e55ed98-6b67-469e-9094-ddde9c676511">

2024-02-14 07:52 UTC, Oniqued commented
<img width="807" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/f9a067a8-3c0e-4d29-a7e0-b7cf5fe1d0e0">

2024-02-14 07:52 UTC, Oniqued commented
<img width="815" alt="image" src="https://github.com/Re-4aliens/backend/assets/98441203/9452f487-06f9-4d87-84e0-4926bc6f46b9">

2024-02-14 16:08 UTC, mjj111 requested changes
고생하셨습니다! 피드백 확인 후 답변 부탁드리겠습니다 😉🙋‍♂️

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/global/property/MatchingRuleProperties.java
> +    private Integer maxTries;
굿굿 입니다~! 
피드백이 잘 수용되었네요!👍

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        matchingTypeGroup.getMatchingTypes().forEach(matchingType -> matchingType.doMatch(participantGroup, languageQueue));
matchingTypeGroup의 메소드인 getMatchingTypes를 살펴보면 아래와 같이 작성하셨더군요!

```
public List<MatchingType> getMatchingTypes() {
        return matchingTypes;
    }
```
  일급 컬렉션으로서 뒀던 matchingTypeGroup이 그저 데이터를 전달만하는 역할을 하고 있습니다. 
  차라리 matchingTypeGroup의 getMatchingTypes 메서드를
  matchParticants 로 아래와 같이 수정하고
  
```
  public void  matchParticants (ParticipantGroup particiants, languageQueue languages) {
        matchingTypes.forEach(typs -> types.doMatch(particiants, languages));
    }
```
  
  MatchingBusiness에서는  아래처럼 메서드 호출하는게 어떨까요?
`  matchingTypeGroup.matchParticants(participantGroup, languageQueue);`

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        participantGroup = ParticipantGroup.from(matchingApplications, matchingRuleProperties);
굿굿~ 깔끔합니다 👍

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/CandidateGroup.java
> +    public static CandidateGroup of(ParticipantGroup participantGroup) {
처음에 왜 Queue를 클래스로 뒀을 까 궁금했는데, 
해당 static of 메서드로 더 깔끔하게 두기 위해서였군요 
더불어 init으로 객체 생성을 관리하니 좋네요

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/controller/dto/response/MatchingResultResponse.java
> +    public static MatchingResultResponse from(MatchingResult matchingResult) {
from 으로 깔끔하게 만드셨네요 👍

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +    public String deleteMatchingApplication(final LoginMember loginMember) {
매칭은 취소니까 Cancel 이 어떨까요? 
메서드가 무슨 로직(delete)을 가지는지는 모르고 
무슨 목적(cancel)인지 알기 더 쉬울 것 같습니다!

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/LanguageQueue.java
> +        Arrays.stream(Language.values()).forEach(language -> languageQueue.put(language, CandidateGroup.init()));
해당 작업이 읽기가 어려워, 무슨 동작을 이해하기 위해 시간이 다소 걸렸습니다.. 🥲
물론 스타일적인 요소지만, 혹시 아래와 같이 **동작의 목적을 메서드 네임으로 명시**하는게 더 읽기 좋지 않을까 의견을 남깁니다..!
```
public static LanguageQueue from(final ParticipantGroup participantGroup) {
    Map<Language, CandidateGroup> languageQueue = new HashMap<>();
    setUpLanguage(languageQueue);
    ...
}

private void setUpLanguage(Map<Language, CandidateGroup> queue) {
    List<Language> languages = Language.values();
    languages.forEach( language -> queue.put( language,  CandidateGroup.init());
}
```

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/LanguageQueue.java
> +                });
해당 코드는 꺼내진 참가자의 선호 언어에 따라 후보자 큐에 넣는 작업으로 이해했습니다. 
그러나 일급컬렉션인 participantGroup이 그저 자신의 데이터를 뱉는 행위만을 하는
getParticipants을 사용하고 있습니다. 

여기서 좀 더 participantGroup이 본인의 책임인 particiants을 직접 관리하도록 한다면!
그리고 행위의 목적을 명시할 수 있다면!
아래와 같이 할 수 있다 생각합니다!🙋‍♂️


```
    public static LanguageQueue from(final ParticipantGroup participantGroup) {
                                   ...
     setUpCandinate();
     }

    private void  setUpCandinate() {
        List<Language> languages = Language.values();
        for ( Language language : languages) {
           List<Particiant> particiants =  participantGroup.getParticiantsByLanguage(language);
           putToCandinateQueue(particiants, language );
        }
    
    private putToCandinateQueue (List<Particiant> particiants, Language language) {
        CandidateGroup candidateGroup = languageQueue.get(language);
        candidateGroup.add(participants);
    }
```



participantGroup 의  코드 
```
    public List<Particant> getParticiantsByLanguage(Language language) {
        ...// Language에 따라 particiant를 리스트로 반환.
    }
```

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +        List<Participant> participants = matchingApplications.stream().map(Participant::of).collect(Collectors.toList());
.collect(Collectors.toList()); 를 Stream의 toList()로 바꾸는게 더 깔끔해보입니다! 🙋‍♂️

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +                .collect(Collectors.toList()));
.collect(Collectors.toList())); -> toList(); 😉

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +    public ParticipantGroup getParticipantsLessThan(final int numberOfPartner) {
메서드 안에 메서드로 작성하는 것보다, 

steram 작업으로 나온 결과물을 List로 명시해주고 
toGroup 결과 명시 후 결과값 전달하는게 좀 더 읽기 편할 것 같습니다!🙋‍♂️

```
    public ParticipantGroup getParticipantsLessThan(final int numberOfPartner) {
        List<Particiants> lessParticiants = participants.stream()
                                                       .filter(getNumberOfPartners() < numberOfPartner)
                                                       .toList();
        ParticipantGroup result = toGroup(lessParticiants);
        return result ;
    }
```

2024-02-14 16:08 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/type/FirstPreferLanguageType.java
> +public class FirstPreferLanguageType implements MatchingType {
MatchingType 인터페이스로 두고,  너무 잘 사용하시네요..😲

2024-02-14 16:29 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +    public List<Participant> getParticipants() {
operateMatching 이후 결과를 가져오는 메서드이기 때문에 
매칭이 된 참가자들을 가져오는 getMatchedPariciants 네이밍이 어떨까요?

2024-02-14 16:51 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/type/SecondPreferLanguageType.java
> +        ParticipantGroup participants = participantGroup.getParticipantsLessThan(matchingRuleProperties.getMaxNormalPartners());
완전히 매칭이 되지 않아 남은 참가자 들이니까 remindedParticiant 로 변수 네이밍 어떠한가요??

2024-02-14 16:51 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/util/validator/LanguageValidator.java
> +        throw new RestApiException(MatchingError.INVALID_LANGUAGE_INPUT);
return 과 throw 의 위치가 반대로 되어야할 것 같습니다!
아래처럼 말이죠!

```
    if (firstPreferLanguage.equals(secondPreferLanguage)) {
        throw new RestApiException(MatchingError.INVALID_LANGUAGE_INPUT);
    }
return true
```

이유는 아래와 같습니다. 
isValid 메서드를 아래로 읽었을 때 
```
만약 입력이 원하지 않는 상황이라면!
입력 예외를 발생시킨다

아니라면
return 괜찮은 입력이다! 
```
는 맥락이 읽기 쉽죠.

하지만 만약 아래처럼 이라면, 어떤 상황에 예외를 뱉는지에 대한 판단이 어려워 집니다. 
이에 따라 변경 시에 어려움을 줄 수도 있죠. 

```
만약 맞는 상황이라면!
맞는 입력이다.

하지만 이외는 다 입력예외!! 
```

 if 절은 일반적으로 조건을 확인하고 특정 작업을 수행하는 데 사용됩니다.
 그렇기 때문에 if 문 안에 예외 케이스와 예외 발생을 같이 두는게 좋은데요, 
 
  if 블록 내부에 예외가 발생하면(첫 번째와 두 번째 선호언어 일치)
  if 의 목적과 예외 상황을 구분하기 어려워집니다.
더불어, 코드를 변경하거나 디버깅할 때 if 절 내부의 예외 처리를 쉽게 놓칠 수 있습니다.

명시적으로 예외를 처리하기 위해서는
 if 문안에 예외가 일어나는 조건을 제시해주고 if 문 안에서 예외를 처리 해주는 것이 더 좋습니다 🙋‍♂️

2024-02-14 17:04 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/util/validator/LanguageCheck.java
> +public @interface LanguageCheck {
오우~ 커스텀 하셨군요! 너무 좋습니다!
validator는 이후에 다른 Request에서도 계속해서 만들 예정이기때문에, 
global 디렉토리에 validator 하나 만들어서 관리하는게 어떨까요?!

2024-02-14 17:04 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingService.java
>      private MatchingRound currentRound;
이건 사용이 안되고 있는 변수인데 없애는게 어떠할까요!?😲

2024-02-14 17:04 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
>  public class MatchingApplicationService {
MatchingApplicationService는 매칭 신청과 신청 내용을 참고하고 있는데요, 
매칭 파트너를 찾는 메서드를 MatchingService에서 호출되고 있습니다.

둘 다 매칭 도메인에 속하고 분리될 필요가 없어 보이는데 혹시 따로 관리하는 이유가 있을까요??
(더불어 MatchingService에 의존관계의 객체들에 MatchingApplicationService가 의존하고 있는 객체가 모두 들어가있습니다! 그렇다면 MatchingService가MatchingApplicationService의 메서드와 같은 맥락(매칭)에서 동작하고 의존하고 있다는걸로 판단되는데 분리된 이유가 궁금합니닷!)

2024-02-14 17:36 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/Language.java
createQueueWith 메서드가 어디에서도 사용하고 있지 않은데 어떤 용도인가요?!

2024-02-14 17:41 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +            CandidateGroup candidateGroup = languageQueue.get(preferLanguage);
languageQueuue의 get을  수정하여,  어떤 것을 가져오는지 명시해주시면 더 좋을 것 같습니다! ex) getCandidateGruopByLanguage()

2024-02-14 17:50 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/business/type/FirstPreferLanguageType.java
> +    private final MatchingRuleProperties matchingRuleProperties;
사용하지 않고 있습니다..! 혹시 사용할 예정인 객체인가요?

2024-02-15 03:14 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/type/FirstPreferLanguageType.java
> +    private final MatchingRuleProperties matchingRuleProperties;
추후 필요할 수 있을 확장성을 위해 넣긴 했어요. 저도 이 부분 의문이 들긴 했는데, 어느 ~Type 클래스는 필요하고, 어느 ~Type 클래스는 필요없고.. 하면 혼란스러울것 같아 넣었어요. 

그러나, 지금 당장 필요없다면 빼는게 맞아 보이네요. 지적 감사합니다 !

2024-02-15 03:14 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +            CandidateGroup candidateGroup = languageQueue.get(preferLanguage);
메서드 네이밍 한번 고민해보겠습니다 !

2024-02-15 03:17 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingService.java
>      private MatchingRound currentRound;
음...? 저게 왜 들어갔지.. 인지 못했네요 ㅠㅠ 삭제하도록 하겠습니다!

2024-02-15 03:17 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/util/validator/LanguageCheck.java
> +public @interface LanguageCheck {
알겠습니다 !

2024-02-15 03:20 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +    public String deleteMatchingApplication(final LoginMember loginMember) {
delete로 할까.. cancel로 할까... 서비스 메서드 네이밍과 컨트롤러 메서드 네이밍을 고민 많이 했었는데, 
그래도 cancel이 나아보이네요.

2024-02-15 03:21 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/model/LanguageQueue.java
> +        Arrays.stream(Language.values()).forEach(language -> languageQueue.put(language, CandidateGroup.init()));
아! 이거 좋네요! 감사합니다

2024-02-15 03:22 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/type/FirstPreferLanguageType.java
> +public class FirstPreferLanguageType implements MatchingType {
이번 리펙토링의 핵심적인 부분이었어요 ㅎㅎ 감사합니다

2024-02-15 03:23 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/type/SecondPreferLanguageType.java
> +        ParticipantGroup participants = participantGroup.getParticipantsLessThan(matchingRuleProperties.getMaxNormalPartners());
좋습니다 !

2024-02-15 03:25 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/util/validator/LanguageValidator.java
> +        throw new RestApiException(MatchingError.INVALID_LANGUAGE_INPUT);
확실히, 제가 작성한 경우에는 생각을 두번 해야하네요.. 
명준님이 말씀하신 대로 하는 것이 더욱 직관적이어 보입니다. 감사합니다 !

2024-02-15 03:52 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/MatchingBusiness.java
> +        matchingTypeGroup.getMatchingTypes().forEach(matchingType -> matchingType.doMatch(participantGroup, languageQueue));
일급 컬렉션에서 꺼내와서 매칭 로직을 동작 시킨다? 이건 좀 이상하긴 하네요! 
일급 컬렉션에게 동작을 수행시키도록 하는 쪽이 맞는것 같습니다! 감사합니다

2024-02-15 05:27 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/model/LanguageQueue.java
> +                });
구조 변경했습니다! 
participantGroup에게 매개변수로 1선호 언어가 language인 모든 participant를 가져오도록 한 후, CandidateGroup을 만들어 LanguageQueue에 넣도록 하니 더욱 보기 좋네요 ㅎㅎ

2024-02-15 05:32 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/model/ParticipantGroup.java
> +    public ParticipantGroup getParticipantsLessThan(final int numberOfPartner) {
'지역 변수 'result'이(가) 중복됩니다'라는 경고가 떠서 이렇게 둔것 같은데.. 
가독성을 위해 변경하도록 하겠습니다

2024-02-15 06:08 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
>  public class MatchingApplicationService {
저는 서비스를 리포지토리 단위로 나누는데요, 
MatchingApplicationService에는 매칭 신청, 매칭 신청 취소, 매칭 신청 내역 조회가 있습니다. 
이렇게 '매칭 신청'에 관한 서비스만 넣고 싶어서 분리했습니다. 

MatchingService에는 지정된 시간에 서버가 매칭 로직을 자동으로 동작시키는 역할을 담고 있으며(추후에 관리자가 수동적으로 매칭 로직을 작동 시킬 수도 있음), 매칭이 성사되었을 경우 매칭 결과를 가져올 수 있는 서비스를 담았습니다. 

MatchingRoundService에는 서버가 자동으로 매칭 회차를 업데이트하는 로직을 담았습니다. 

위 세 서비스 클래스는 각각 사용되는 시점이 다릅니다.
1. ApplicationService는 접수 시간인 월, 목요일에 집중적으로 사용됨 
2. MatchingService는 매칭 실행 시간인 월, 목요일에 각각 한번, 또는 매칭 결과를 조회할때(매일) 사용됨
3. RoundService는 매칭 회차가 업데이트되는 시간인 월, 목에 각각 한번 사용됨. 그 외 사용될 일 없음
에 따라 호출 빈도 또한 각각 명확하게 다르기 때문에 분리했습니다. 

컨트롤러에서 접근하는 매칭 코드를 MatchingService에 모두 넣는다면 MatchingService코드가 너무 비대해질 것을 우려했기 때문에 분리한 이유도 있습니다😥

위에따라 맥락을 분리한다면, Controller를 MatchingApplicationController, MatchingController로 분리하는것을 고려해보려고 합니다.

2024-02-15 06:19 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/business/model/Language.java
충돌 해결하면서 미처 보지 못한 부분 같습니다 ㅠㅠ 죄송합니다! 제거하겠습니다

2024-02-15 16:57 UTC, mjj111 approved these changes

2024-02-15 23:00 UTC, merged