Feat/#69 matching domain external api integration
Re-4aliens/backend pull request #71
Opened 2024-02-16 05:15 UTC by Oniqued

## 🤨 Motivation

- #67 
- #66 
- #65 
- #70 

## 🔑 Key Changes 

- 매칭 서비스에 FCM 알림 서비스, 채팅방 개설 이벤트 발행 요청이 필요해짐에 따라 이를 구현 및 테스트 합니다.
- FCM 알림 서비스 구현
- 채팅방 개설 이벤트 발행 코드 구현
- 저장 로직이 for문에서 stream으로 변경
- 통합 테스트 통과
- docs를 작성
- 사용자 엔티티의 매칭 상태를 변경

## 🙏 To Reviewers 

-

2024-02-19 13:04 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
> +                .map(MatchingApplication::getMember)
이게 객체지향이죠! 깔끔합니다 👍

2024-02-19 13:06 UTC, mjj111 commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +    public void matched() {
1차에서 신청한 인원이 2차에서 매칭이 되면 NOT_APPLIED_MATCHED 아닌가요?🤔

2024-02-19 14:12 UTC, Oniqued commented
이게 로컬에서는 실행시간이 빨라서 테스트가 모두 통과하는데, git이 테스트 하는데는 20분(?!)이나 걸려서, 그 사이에 누군가 테스트를 돌리면 테스트 디비에서 데이터를 가져올때 계속 엉킵니다. 아마 지금은 일시적으로 테스트 실패라고 뜰거에요

2024-03-01 16:06 UTC, coke98 approved these changes
매칭 영역과 채팅 영역을 이벤트로 분리시켰어도 채팅방, 차단, memberPair같은 중간 영역때문에 매칭에서 채팅 도메인 영역의 코드를 하나하나 알아야하는 상황이 발생했네요. 하나하나 체리픽해가면서 시도해보신것 같은데, 고생하신게 보입니다.
 
 두 영역에서 서로 간섭하지 않고 개발이 가능한 방법이 없었을지, 고민이 되는 부분이었네요. 이벤트를 문서화를 한다던가, 채팅방, 차단관련 코드등 타 도메인에서 쓰일 수 있는 코드를 먼저 작성 후 머지를 한다던가, 그러지 못해 협업에 문제가 생길 수 있다는 점을 보고, 제 코드를 한번 더 돌아보게 되었던 것 같습니다.
 
 이 외 매칭 영역 로직은 확인했습니다~!👍 고생하셨습니다

2024-03-01 16:06 UTC, coke98 commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +            status = MatchingStatus.APPLIED_NOT_MATCHED;
분기문이 2개인 함수들을 보면서 MatchingStatus가 LastMatchingStatus(Matched,Not_Matched), NextMatchingStatus(applied,not_applied)로 나누어져있다면 하나의 분기분으로 모두 작성할 수 있지 않았을까 싶네요!

2024-03-01 16:06 UTC, coke98 commented on src/main/java/com/aliens/backend/chat/controller/dto/event/ChatRoomExpireEvent.java
> +public record ChatRoomExpireEvent(Set<MemberPair> matchedPairs) {
고민중인게 현재 기능 내에서 채팅방을 만료시키는 경우는 새로운 채팅방을 만들기 전일텐데, 그럼 이전의 채팅방 모두를 만료시키는 방식은 어떨까요? 멤버들로 모든 채팅방을 만료시키기에는 DB접근이 꽤나 많아질 것 같다고 생각했네요!

2024-03-01 16:06 UTC, coke98 commented on src/main/java/com/aliens/backend/global/property/MatchingTimeProperties.java
> +    private Long tuesdayRequestAvailableHours;
해당 시간대와 조건을 보여주니 코드만 보고도 매칭 요구사항을 알 수 있는 장점이 있네용

2024-03-01 16:06 UTC, coke98 commented on src/main/java/com/aliens/backend/mathcing/service/event/MatchingEventPublisher.java
> +public class MatchingEventPublisher {
퍼블리셔 클래스를 따로 두셨군요! 👍

2024-03-03 01:21 UTC, mjj111 requested changes
고생하셨습니다! 리뷰 답변 후 머지하도록 하겠습니다 🙆‍♂️

2024-03-03 01:21 UTC, mjj111 commented on src/main/java/com/aliens/backend/chat/domain/repository/ChatRoomRepository.java
> +    @Query("SELECT c FROM ChatRoom c JOIN c.participants p WHERE p.member.id = :memberId")
굿~! 추후에 QueryDSL 적용 후 바로 수정할 수 있겠군요

2024-03-03 01:21 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +        cancelForMatching(matchingApplication);
네이밍 센스 굿 👍

2024-03-03 01:21 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +        return matchingApplicationRepository.findByMatchingRoundAndMemberId(matchingRound, loginMember.memberId())
따로 쿼리문을 작성해야하지만, Member를 호출하고 findByMatchingRoundAndMember() 를 사용하는 것보다 쿼리문이 하나 줄어드네요 !

2024-03-03 01:21 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
> +        Member matchingMember = matchingResult.getMatchingMember();
지금 모습을 보면 matchingResult에서 멤버를 찾는 동작에, 찾은 멤버를 매칭 시켜주고 있네요.

matchingResult에서 matchEach() 라는 함수를 만들고,
해당 함수 안에서 갖고 있는 두개의 객체에 member.matched() 함수를 사용하는 방식은 어떨까요?

2024-03-03 01:21 UTC, mjj111 commented on src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
> +        Member matchingMember = matchingResult.getMatchingMember();
해당 코드도 이전 리뷰에 남긴 것 처럼 matchingResult에서 해결해주면 더 좋을 것 같습니다 !

2024-03-03 01:21 UTC, mjj111 commented on src/main/resources/application-matching.yml
> +    update-date: 0 0 0 * * TUE,FRI # 매칭 회차 업데이트 시간 : 화, 금 0시 (접수 시작 시간)
yml에서 매칭 시간을 정할 수 있다니... 
너무 좋습니다 🙆‍♂️👍

2024-03-03 01:30 UTC, Oniqued commented on src/main/java/com/aliens/backend/auth/domain/Member.java
> +            status = MatchingStatus.APPLIED_NOT_MATCHED;
아..! 이 그부분을 미처 생각 못했군요! 이 부분을 깊게 생각하지 못했네요 😱

2024-03-03 01:33 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
> +        return matchingApplicationRepository.findByMatchingRoundAndMemberId(matchingRound, loginMember.memberId())
맞아요 .. 쿼리를 작성해야하는 부분이 있었지만, 따로 MemberRepository에서 Id로 멤버 객체를 찾아오고 갖다 쓰지 않고, 
그냥 memberId로 찾아오게 하는게 DB를 한번 더 접근하지 않게되어서 좋다고 생각했어요!

2024-03-03 01:35 UTC, Oniqued commented on src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
> +        Member matchingMember = matchingResult.getMatchingMember();
오... 이걸 생각 못했다니... 
바로 수정 하겠습니다!

2024-03-03 01:37 UTC, Oniqued commented on src/main/java/com/aliens/backend/chat/controller/dto/event/ChatRoomExpireEvent.java
> +public record ChatRoomExpireEvent(Set<MemberPair> matchedPairs) {
좋습니다! 현석님이 제안해주신 방식으로 많이 고민해보고 해당 로직 수정해보도록 하겠습니다!

2024-03-06 05:42 UTC, mjj111 approved these changes

2024-03-06 05:43 UTC, merged

2024-03-06 10:34 UTC, Oniqued commented on src/main/java/com/aliens/backend/chat/controller/dto/event/ChatRoomExpireEvent.java
> +public record ChatRoomExpireEvent(Set<MemberPair> matchedPairs) {
> 고민중인게 현재 기능 내에서 채팅방을 만료시키는 경우는 새로운 채팅방을 만들기 전일텐데, 그럼 이전의 채팅방 모두를 만료시키는 방식은 어떨까요? 멤버들로 모든 채팅방을 만료시키기에는 DB접근이 꽤나 많아질 것 같다고 생각했네요!

음 그런데, 이전에 개설된 채팅방인지 어떻게 알고 만료시킬 수 있을까요 ?