Feat/#29 board 도메인 구현
Re-4aliens/backend pull request #86
Opened 2024-04-14 14:15 UTC by mjj111

## 🤨 Motivation

- #85 
- #29 

## 🔑 Key Changes 

- 

## 🙏 To Reviewers 

-

2024-05-01 07:27 UTC, suhyun0918 requested changes
정말 많은 코드 작업량이네요! 
대단히 고생 많으셨습니다 🥹

코드 잘 확인했습니다! 
자잘한 오타나, 휴먼 에러, 코드 컨벤션, 메서드 분리 정도에 관해서 리뷰가 이루어졌습니다! 

특히 페이징이랑 대댓글을 구현 하신 부분이 제겐 새로워 흥미로웠습니다 ㅎㅎ 

리뷰 확인 부탁드릴게요!

2024-05-01 07:27 UTC, suhyun0918 commented on src/test/java/com/aliens/backend/docs/BoardRestDocsTest.java
> +                        .contentType(MediaType.APPLICATION_JSON))
특정 카테고리로 게시글을 검색하는 기능으로 보입니다!

카테고리만 이용해서 검색하는 것이 아니라, 검색 키워드도 입력해서 검색하나요?
(검색어 && 카테고리)

2024-05-01 07:27 UTC, suhyun0918 commented on src/test/java/com/aliens/backend/docs/MarketBoardRestDocsTest.java
> +                        ),
게시 이미지 파일 크기나 갯수에는 제한이 없을까요?

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/controller/MarketController.java
> +        boardService.changeMarketBoard(boardId, request, loginMember);
47번줄의 장터 게시글ID를 의미하는 매개변수명은 id고, 
61번줄의 장터 게시글ID는 매개변수명이 boardId 군요! 

하나로 통일하는 편이 좋아보입니다!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/enums/ProductStatus.java
> +    USED("사용감 있음");
ProductStatus도 좋지만 
다음번엔 ProductQuality 라는 네이밍도 좋았을 것 같아요 ! 
사소하니 패스!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/Great.java
> +        return great;
return new Great(board, member); 로 만들지 않고, 따로 값을 set 하신 이유가 있으실까요?!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/repository/GreatRepository.java
> +    long deleteGreatByMemberAndBoard(Member member, Board board);
delete 쿼리에 long 타입 반환을 받으신 이유가 궁금해요! 

몇개의 행이 삭제되었는지 확인하는 용도인가요?
그렇다면, 몇개의 행이 삭제되었다는 데이터를 어디다가 활용할 예정이신지 궁금합니다!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/repository/custom/GreatCustomRepositoryImpl.java
> +    private final QGreat qGreat = QGreat.great;
스프링이 3.x로 넘어오면서 
쿼리DSL의 Q클래스 사용법이 많이 달라졌군요 
적용하시느라 고생 많으셨을 것 같아요...

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/GreatService.java
> +        if (isAlreadyExit(board, member)) return;
이 제어문은 구글 자바 컨벤션에 어긋나는것 같습니다. 

**조건문/반복문**
조건문과 반복문이 한 줄로 끝나더라도 중괄호를 사용해야 한다.
```
if ("A".equals(type)) {             //(O)
    return false;
}

if ("A".equals(type)) return false; //(X)
```

출처: [https://lanuarius19.tistory.com/entry/JAVA-자바-코드-컨벤션](https://lanuarius19.tistory.com/entry/JAVA-%EC%9E%90%EB%B0%94-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98)

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/GreatService.java
> +    }
isAlreadyExist 를 보면 **(<< 잘 보니 Exist 인데 Exit 로 적으셨군요!)**
본인이 좋아요를 이미 눌렀는지 안눌렀는지 true or false를 반환하는 메서드 같아요! 

그런데, 실제 하는 역할이 좋아요를 이미 눌렀으면 좋아요를 취소하는 기능을 같이 하고 있군요 

(1) 이미 좋아요를 눌렀는지 확인 하는 메서드
(2) 좋아요를 눌렀다면 취소하는 메서드 
로 분리하는건 어떨까요?

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/Comment.java
> +public class Comment {
그렇군요.... 
저희 서비스 댓글 구조가 
1
-2(부모:1)
--3(부모:2)
4
-5(부모:4)
--6(부모:5)
이렇게 되는건가요?

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/CommentService.java
> +            if (!comment.isParent()) continue;
이것도 자바 컨벤션을 확인해보셔야할것 같아요!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/CommentService.java
> +            if(childrenComment != null && !childrenComment.isEmpty()) {
조건을 읽기 쉽도록 메서드로 분리하는건 어떨까요?

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/CommentService.java
> +        if(!comment.isWriter(loginMember.memberId())) throw new RestApiException(BoardError.INVALID_COMMENT_WRITER);
조건절 아래 라인이 하나밖에 없더라도 {}를 붙이는게 구글 자바 컨벤션에 맞아보입니다!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/BoardService.java
> +    }
```
if (!board.isWriter(loginMember.memberId())) {
            throw new RestApiException(BoardError.NOT_WRITER);
}
```

이 코드가 중복되는것 같네요! 메서드로 빼는건 어떨까요? 

checkWriter(loginMember);
같은 방법도 좋을 것 같아요! 

```
private void checkWriter(final LoginMember loginMember) {
     if (!board.isWriter(loginMember.memberId())) {
            throw new RestApiException(BoardError.NOT_WRITER);
     }
}
```

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/service/BoardReportService.java
> +        }
매직넘버 보단 환경 변수(@Value)로 받거나, 
MAX_REPORT_COUNT 같은 상수도 좋아보여요!

2024-05-01 07:27 UTC, suhyun0918 commented on src/main/java/com/aliens/backend/board/domain/BoardImage.java
> +    String url;
!!!!!!!!!!!!!
접근 제한자를 빼먹으신것 같군요!

2024-05-01 07:36 UTC, suhyun0918 requested changes
제가 놓쳤던 걸 수도 있지만
코드에서 파일을 업로드 하는 부분에서 

> **파일의 확장자를 제한**
(이미지인데 .jpg, .png, 외의 파일을 업로드 한 경우)

> **이미지 용량을 제한(대용량 파일 업로드)하거나** (시스템 자원 소모 Dos)

> 이미지 **업로드 횟수를 제한**

하는 코드가 보이지 않았습니다. 

파일 업로드에서 이 부분은 대단히 중요한 사안입니다. 

파일을 업로드 할때 확장자를 제한하지 않았을 경우 서비스에 매우 치명적인 취약점이 될 수 있습니다.
(이는 명준님도 잘 아실 부분이라고 생각합니다. ex: XXS 공격, .php 파일을 업로드 하여 서버 사이드 코드 실행 등)

프론트에서 이를 제한을 한다고 해도 
프론트에선 얼마든지 조작이 가능하므로 백엔드단에서 검증을 해주는 부분이 필수적이라고 생각합니다. 

환경변수를 통해서 
- 파일 업로드 갯수 제한
- 허용 가능한 확장자
- 허용 가능한 이미지 크기

를 정의하여 이를 활용하는건 어떨까요??

2024-05-01 07:44 UTC, suhyun0918 commented
고생많으셨습니다! 🤗

2024-05-01 10:21 UTC, mjj111 commented on src/test/java/com/aliens/backend/docs/MarketBoardRestDocsTest.java
> +                        ),
2개 제한이 필요합니다! 막을 수 있도록 검증 로직 추가하도록 하겠습니다 🙆‍♂️

2024-05-01 10:22 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/enums/ProductStatus.java
> +    USED("사용감 있음");
아뇨! ProductQuality 이 더 네임으로 좋은거같네요 수정하도록 하겠습니다

2024-05-01 10:23 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/service/GreatService.java
> +        if (isAlreadyExit(board, member)) return;
알고리즘 작성하던 방식이 녹여졌네요..! 
컨벤션에 맞게 수정하도록 하겠습니다🙆‍♂️

2024-05-01 10:24 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/repository/GreatRepository.java
> +    long deleteGreatByMemberAndBoard(Member member, Board board);
필요없는 메서드네요! 지우도록 하겠습니다.

2024-05-01 10:26 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/service/GreatService.java
> +    }
프론트에서 현재 해당 방법에 대해 분리가 되어있지 않아, 
추가 작업을 최소하하고자 좋아요에 대한 api 하나로 취소와 좋아요를 기능이 하나에서 동작하도록 했습니다 🥲

2024-05-01 10:27 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/Comment.java
> +public class Comment {
네! 맞습니다. 
본래는 Entity에서 관계맺어 두고자했으나... 
이전 API 에서 위와같이 관리하고 있어서 프론트 작업 최소화를 위해 위와같이 두었습니다!

2024-05-01 10:28 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/service/CommentService.java
> +            if(childrenComment != null && !childrenComment.isEmpty()) {
if 문안에 조건이 두 개가 되니, 메서드로 분리하는게 더 좋을것 같네요!

2024-05-01 10:29 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/service/BoardService.java
> +    }
참고해서 분리하도록 하겠습니다!

2024-05-01 10:30 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/service/BoardReportService.java
> +        }
저걸 상수로 안뒀군요..!
찾아주셔서 감사합니다. Value로 가져와서 상수로 관리하도록 하겠습니다!

2024-05-01 10:30 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/BoardImage.java
> +    String url;
홀리... 찾아주셔서 감사합니다.

2024-05-01 10:33 UTC, mjj111 commented on src/test/java/com/aliens/backend/docs/BoardRestDocsTest.java
> +                        .contentType(MediaType.APPLICATION_JSON))
네 맞습니다! 
원하는 카테고리와 검색어 기반으로 검색하도록 합니다

2024-05-02 00:26 UTC, suhyun0918 approved these changes

2024-05-02 20:36 UTC, coke98 approved these changes
저도 오타나 네이밍 관련해서 주로 리뷰했습니다! 나머지는 너무 잘 작성해주셨고, 수현님께서 또 잘 봐주셨더라구요. 고생하셨습니다!

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/controller/CommentController.java
> +
RequestMapping("/comments"), ("/great")으로 묶어도 괜찮을 듯!

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/controller/GreatController.java
> +    public SuccessResponse<?> greatAtBoard(@RequestParam("board-id") final Long boardId,
좋아요에 관한 행위에 따라 네이밍을  getLike~ addLike~와 같은 (행위 + 객체) 표현을 쓰면 더 명확할 수 있을 것 같았어요 (+ great보다 like가 소셜미디어의 관용적 표현이라고 생각했습니다!)

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/controller/dto/response/CommentResponse.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
사용하는 이유가 궁금해요! 응답에서 필요한 상황이 발생하나요?

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/domain/Board.java
> +    public void minusGreatCount() {
명사, 형용사인 minus대신 reduceGreatCount 표현도 자연스러울 것 같아요. 네이밍이 제일 어렵네요..

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/domain/enums/ProductStatus.java
> +    USED("사용감 있음");
Status는 판매되었는지 아닌지 여부와 혼동이 있을 것 같아요 Quality가 명확할 것 같습니다!

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/domain/repository/BoardRepository.java
> +    List<Board> findAlLWithMarketInfo();
findAlL -> findAll 👀(쉬프트키 일찍 누르셨습니다)

2024-05-02 20:36 UTC, coke98 commented on src/test/java/com/aliens/backend/board/service/GreatServiceTest.java
> +    @DisplayName("게시글 좋아요 등록")
게시글 좋아요 취소 상황도 테스트 해보면 좋을 것 같아요~!

2024-05-02 20:36 UTC, coke98 commented on src/main/java/com/aliens/backend/board/service/GreatService.java
> +    }
API를 분리할 필요는 없을 것 같고, 대신 isAlreadyExist 한 메서드 내에서 검증과 데이터 변경이 동시에 이루어져 있는게 문제가 될 수 있을 것 같아요. isAlreadyExist는 조건문에 쓰이기위한 boolean 반환값 만을 가져오길 바라고 있을텐데, 데이터 변경이라는 sideEffect가 발생하는거니까요. 

데이터 변경파트인
```
greatRepository.deleteGreatByMemberAndBoard(member, board);
board.minusGreatCount();
```
는 isAlreadyExist 메서드를 호출하고 있는 greatAtBoard 메서드 조건문 내에서 처리하는게 사이드 이펙트를 줄일 수 있을 것 같습니다!

2024-05-03 14:57 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/controller/GreatController.java
> +    public SuccessResponse<?> greatAtBoard(@RequestParam("board-id") final Long boardId,
like가 SQL에서 쓰이는 명령어라서 엔티티 네이밍이 불가합니다!
그래서 다른 의미로 찾아볼까하다가 한 단어로 표현하는게 좋을 것으로 판단하여 Great로 사용하게되었습니다🙋‍♂️

2024-05-03 14:57 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/controller/dto/response/CommentResponse.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Comment에서 Doc 작업시에 생기는 문제 때문에 넣었었습니다만.. 빼도 될거같군요 제거하도록 하겠습니다!

2024-05-03 14:58 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/Board.java
> +    public void minusGreatCount() {
저런.. minus가 동사인줄 알았네요 ! reduce로 변경할 수 있도록 이슈 파놓도록 하겠습니다!

2024-05-03 14:59 UTC, mjj111 commented on src/main/java/com/aliens/backend/board/domain/repository/BoardRepository.java
> +    List<Board> findAlLWithMarketInfo();
ㅋㅌㅋㅋㅋㅋㅋ 아 ㅋㅋ ㅠ  찾아주셔서 감사합니다... 네이밍 이슈파서 수정하도록 하겠습니다.

2024-05-03 15:00 UTC, mjj111 commented on src/test/java/com/aliens/backend/board/service/GreatServiceTest.java
> +    @DisplayName("게시글 좋아요 등록")
프론트 작업 최소화를 위해 좋아요만 넣어놨습니다!
좋아요 계속 누르면 좋아요상태에서 취소로 동작하도록 현재 구현되어있어요!

2024-05-03 15:01 UTC, merged